### ISSUE TITLE
Dates in an unambiguous Format

### ISSUE THREAD

**Issue by Chwiggy** [stevebot-project/steve#12] opened 2020-04-03 14:28 UTC
Currently dates are displayed as MM-DD-YYYY which is uniquely North American and quite ambiguous with the European DD-MM-YYYY. 
To make it more readable without confusion I'd suggest either following YYYY-MM-DD or if there's a preference to do Month-Day-Year to adopt Month-DD-YYYY or MON-DD-YYYY with either the full name of the month or its 3 letter abbreviation

**Comment by jwford** [comment] 2020-04-03 15:12
Duplicate of #11, will link both issues in the commit that fixes

**Closed as completed** 2020-04-04 13:31 UTC
Labels: duplicate
